routes/web.php
<?php

use App\Http\Controllers\GameController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [GameController::class, 'index'])->name('game.play');
Route::get('/stats', [GameController::class, 'index'])->name('stats');

Route::prefix('game')->group(function() {
    Route::post('/start', [GameController::class, 'start'])->name('game.start');
    Route::post('/answer', [GameController::class, 'answer'])->name('game.answer');
    Route::get('/question', [GameController::class, 'question'])->name('game.question');
    Route::get('/over', [GameController::class, 'over'])->name('game.over');
});

app/Models/Game.php
<?php

namespace App\Models;

use App\Guesser;
use App\Questions\Question;
use Illuminate\Database\Eloquent\Model;

class Game extends Model
{
    protected $casts = ['questions' => 'json'];
    protected $fillable = ['questions', 'level', 'questions_asked'];

    public static function boot()
    {
        parent::boot();

        static::updating(function (self $game) {
            $game->questions_asked = count($game->questions);
        });
    }
    public function getQuestionsAttribute(?string $questions): array
    {
        $questions = $questions ? json_decode($questions, true) : [];

        return array_map(
            function (array $questionData) {
                $questionClass  = Guesser::getValidQuestions()[$questionData['identifier']];
                unset($questionData['identifier']);

                /** @var Question $questionObject */
                $questionObject = new $questionClass();
                $questionObject->hydrate($questionData);

                return $questionObject;
            },
            $questions
        );
    }

    public function addQuestion(Question $question): void
    {
        $questions = $this->questions ?? [];
        $this->questions = [...$questions, $question];
    }

    public function getGuessesAttribute(): int
    {
        return count($this->questions) + 1;
    }
}

app/Http/Controllers/GameController.php
<?php

namespace App\Http\Controllers;

use App\Guesser;
use App\Models\Game;
use App\Questions\Question;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class GameController extends Controller
{
    private array $levels = [
        [
            'label' => 'Easy',
            'range' => [0, 100],
        ],
        [
            'label' => 'Medium',
            'range' => [0, 250],
        ],
        [
            'label' => 'Hard',
            'range' => [0, 1000],
        ],
        [
            'label' => 'Extreme',
            'range' => [0, 500000],
        ],
    ];

    public function index()
    {
        return view('game.start', [
            'levels' => $this->levels,
        ]);
    }

    public function start(Request $request)
    {
        $validatedData = $request->validate([
            'level' => [
                'required',
                Rule::in(array_keys($this->levels)),
            ],
        ]);

        $game = Game::create([
            'level' => $validatedData['level'],
        ]);

        $request->session()->put('gameId', $game->id);

        return redirect(route('game.question'));
    }

    public function question(Request $request)
    {
        $game = $this->getGame($request);
        $level = $this->levels[$game->level];

        $guesser = new Guesser($level['range'][0], $level['range'][1], $game->questions);

        if ($guesser->hasOneOptionLeft()) {
            return redirect(route('game.over'));
        }

        $question = $guesser->getQuestionToAsk($request->session()->get('questionClass'));

        $request->session()->put('questionClass', get_class($question));

        return view('game.question', compact('game', 'guesser', 'question'));
    }

    private function getGame(Request $request): Game
    {
        return Game::findOrFail($request->session()->get('gameId'));
    }

    public function answer(Request $request)
    {
        $validatedData = $request->validate([
            'answer' => 'required',
            'question' => 'required',
            'context' => 'array',
        ]);

        $game = $this->getGame($request);

        $question = Guesser::getValidQuestions()[$validatedData['question']];

        /** @var Question $question */
        $question = new $question();
        $question->setAnswer($validatedData['answer']);
        $question->setContext($validatedData['context'] ?? []);

        $game->addQuestion($question);
        $game->save();

        return redirect(route('game.question'));
    }

    public function over(Request $request)
    {
        $game = $this->getGame($request);
        $level = $this->levels[$game->level];

        $guesser = new Guesser($level['range'][0], $level['range'][1], $game->questions);

        $number = $guesser->getPossibleValues()[0];

        return view('game.over', compact('game', 'number'));
    }
}

resources/views/game/over.blade.php
@include('header')
<h1>Your number is:</h1>

<p style="font-size: 150px; margin-bottom: 25px;">{{ number_format($number) }}</p>

<a href="{{ route('game.play') }}" class="button">Play again</a>

<audio autoplay>
    <source src="/yay.mp3" type="audio/mpeg">
</audio>
@include('footer')

resources/views/game/question.blade.php
@include('header')
<div style="float: left; width: 70%">
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <h1>{{ $question->getQuestion() }}</h1>

    <form action="{{ route('game.answer') }}" method="post" id="question-form">
        @csrf
        <div class="radio">
            @foreach($question->getPossibleAnswers() as $answer => $name)
                <label for="{{ $answer }}Answer">{{ $name }}</label>
                <input
                    type="radio"
                    name="answer"
                    id="{{ $answer }}Answer"
                    value="{{ $answer }}"
                    onclick="submitForm('question-form')">
            @endforeach
        </div>
        <input type="hidden" name="question" value="{{ $question->getIdentifier() }}">
        @foreach($question->getContext() as $key => $value)
            <input type="hidden" name="context[{{ $key }}]" value="{{ $value }}">
        @endforeach
    </form>

    <button onclick="location.reload()" style="margin-top: 50px;">Give me another question</button>
</div>
<div style="float: right; width: 30%; text-align: center;">
    <div>
        <h1>Questions asked:</h1>
        <p style="font-size: 75px;">{{ $game->guesses }}</p>
    </div>
    <div>
        <h2>Possible answers:</h2>
        <div id="possible-answers">
            @foreach($guesser->getPossibleValuesAsRanges() as $range)
                {{ $loop->first ? '' : ', ' }}
                {{ $range[0] }}
                @if(count($range) === 2)
                    - {{ $range[1] }}
                @endif
            @endforeach
        </div>
    </div>
</div>
@include('footer')

resources/views/game/start.blade.php
@include('header')
<h1>Select a difficulty level</h1>

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('game.start') }}" method="post" id="start-form">
    @csrf
    <div class="radio">
        @foreach($levels as $index => $level)
            <label for="{{ $index }}Answer">
                {{ $level['label'] }}<br>{{ number_format($level['range'][0]) }} - {{ number_format($level['range'][1]) }}
            </label>
            <input
                type="radio"
                name="level"
                id="{{ $index }}Answer"
                value="{{ $index }}"
                onclick="submitForm('start-form')">
        @endforeach
    </div>
</form>
@include('footer')